apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: spring-boot-ui-trigger-pipeline-template
spec:
  params:
  - name: gitrepository.url
  - name: gitrepository.fullname
  - name: gitrevision
  - name: commit.prior_revision
  - name: commit.ref
  - name: commit.id
  - name: commit.date
  - name: commit.message
  - name: commit.author
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: spring-boot-ui-run-pr-tr-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: spring-boot-ui
      workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: spring-boot-ui
      params:
        - name: APP_NAME
          value: spring-boot-ui
        - name: GIT_REPO
          value: 'https://github.com/dyangcht/query-labs.git'
        - name: GIT_REVISION
          value: v1.2
        - name: IMAGE_NAME
          value: 'image-registry.openshift-image-registry.svc:5000/demo/spring-boot-ui'
        - name: PATH_CONTEXT
          value: spring-boot-ui
        - name: VERSION
          value: openjdk-11-el7
        - name: templateFileName
          value: build/template/deploy-app-template.yaml
        - name: url
          value: $(tt.params.gitrepository.url)
        - name: gitrepository_fullname
          value: $(tt.params.gitrepository.fullname)
        - name: revision
          value: $(tt.params.gitrevision)
        - name: commit_prior_revision
          value: $(tt.params.commit.prior_revision)
        - name: commit_ref
          value: $(tt.params.commit.ref)
        - name: commit_id
          value: $(tt.params.commit.id)
        - name: commit_date
          value: $(tt.params.commit.date)
        - name: commit_message
          value: $(tt.params.commit.message)
        - name: commit_author
          value: $(tt.params.commit.author)
